server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/taste_notes?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true&tinyInt1isBit=false&allowLoadLocalInfile=true&allowLocalInfile=true&allowUrlInLocalInfile=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublicKeyRetrieval=true&allowPublic
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  ldap:
    embedded:
      validation:
        enabled: true


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.zfh.entity # 扫描的包
  mapper-locations: classpath*:mapper/*.xml
com:
  zfh:
    jwt:
      user-secret: zfh
      admin-secret: zfh
      user-token-name: authorization
    captcha:
      user-enable: false
      user-length: 5

logging:
  level:
    com.zfh.filter.UsernamePasswordJsonFilter: off

